env:
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - '@typescript-eslint'
  - simple-import-sort

rules:
  indent: ['error', 4, { SwitchCase: 1 }]
  no-console: 0
  import/extensions: 0
  simple-import-sort/imports: ['warn']
  no-shadow: 0
  '@typescript-eslint/no-unused-vars': 2
  '@typescript-eslint/no-shadow': 2
  max-len: ['warn', 200]
